relsem(cible,courir,marathonien).
relsem(agent,tricheur,tricher).
relsem(cible,tricher,champion).
relsem(cible,tricher,sportive).
relsem(agent,sportif,sauter).
relsem(cible,défendre,essai).
relsem(cible,tricher,sportif).
relsem(agent,sportif,abandonner).
relsem(cible,tricher,tricheur).
relsem(agent,sportif,courir).
relsem(cible,battre,champion).
relsem(agent,champion,mener).
relsem(cible,gagner,champion).
relsem(cible,courir,basketteur).
relsem(cible,disputer,sportif).
relsem(cible,doper,sportif).
relsem(cible,vaincre,sportif).
relsem(cible,rencontrer,sportif).
relsem(cible,battre,sportif).
relsem(cible,courir,sprinter).
relsem(cible,mener,champion).
relsem(cible,abandonner,sportif).
relsem(agent,sportif,gagner).
relsem(cible,défendre,basketteur).
relsem(agent,marathonien,courir).
relsem(agent,sportif,jouer).
relsem(agent,sprinter,courir).
relsem(agent,sportif,battre).
relsem(agent,sportif,rencontrer).
relsem(agent,sportif,vaincre).
relsem(cible,nager,capitaine).
relsem(agent,sportif,doper).
relsem(agent,ballon,naviguer).
relsem(cible,supporter,supporteur).
relsem(cible,tirer,tireur).
relsem(agent,sportif,disputer).
relsem(agent,tireur,tirer).
relsem(cible,marquer,footballer).
relsem(agent,supporteur,supporter).
relsem(cible,jouer,batteur).
relsem(cible,marquer,volleyeur).
relsem(cible,marquer,basketteur).
relsem(agent,essai,défendre).
relsem(agent,basketteur,courir).
relsem(agent,sportif,pratiquer).
relsem(cible,tirer,gardien de but).
relsem(agent,gardien de but,tirer).
relsem(cible,courir,sprinteur).
relsem(agent,champion,gagner).
relsem(cible,pratiquer,sportif).
relsem(agent,capitaine,nager).
relsem(cible,courir,sprinter).
relsem(agent,sprinter,courir).
relsem(cible,tirer,basketteur).
relsem(agent,footballer,marquer).
relsem(agent,footballeur,marquer).
relsem(agent,footballeur,courir).
relsem(agent,batteur,jouer).
relsem(agent,volleyeur,marquer).
relsem(agent,basketteur,marquer).
relsem(agent,footballeuse,marquer).
relsem(agent,footballeuse,tirer).
relsem(agent,footballeuse,jouer).
relsem(agent,sportif,lancer).
relsem(agent,sportif,perdre).
relsem(agent,sportif,nager).
relsem(cible,marquer,marqueur).
relsem(cible,lancer,sportif).
relsem(cible,sauter,sportif).
relsem(cible,gagner,sportif).
relsem(cible,perdre,sportif).
relsem(cible,courir,sportif).
relsem(agent,marqueur,marquer).
relsem(agent,champion,battre).
relsem(agent,sportif,tricher).
relsem(agent,sportive,tricher).
relsem(agent,footballeur,tricher).
relsem(cible,marquer,footballeur).
relsem(cible,courir,footballeur).
relsem(cible,jouer,sportif).
relsem(cible,lancer,handballeur).
relsem(cible,courir,footballeuse).
relsem(agent,champion,tricher).
relsem(cible,nager,sportif).
relsem(cible,tricher,footballeur).
relsem(cible,naviguer,ballon).
relsem(agent,sprinteur,courir).
relsem(cible,perdre,club de sport).
relsem(agent,club de sport,perdre).
relsem(cible,tirer,footballeuse).
relsem(cible,nager,barreau).
relsem(cible,jouer,footballeuse).
relsem(cible,défendre,essai).
relsem(cible,marquer,footballeuse).
relsem(agent,barreau,nager).
relsem(agent,essai,défendre).
