relsem(agent,kayac,naviguer).
relsem(cible,courir,marathonien).
relsem(cible,nager,maitre-nageur).
relsem(agent,tricheur,tricher).
relsem(cible,tricher,concurrent).
relsem(cible,tricher,sportive).
relsem(agent,skieur,glisser).
relsem(agent,patineur,glisser).
relsem(agent,navigateur,naviguer).
relsem(cible,battre,concurrent).
relsem(agent,sportif,sauter).
relsem(cible,tricher,sportif).
relsem(agent,sportif,abandonner).
relsem(cible,tricher,tricheur).
relsem(agent,sportif,courir).
relsem(cible,doper,concurrent).
relsem(cible,disputer,concurrent).
relsem(cible,courir,basketteur).
relsem(cible,disputer,sportif).
relsem(cible,doper,sportif).
relsem(cible,vaincre,concurrent).
relsem(cible,vaincre,sportif).
relsem(cible,plonger,nageur).
relsem(cible,rencontrer,sportif).
relsem(cible,battre,sportif).
relsem(cible,abandonner,sportif).
relsem(cible,glisser,patineur).
relsem(cible,glisser,skieur).
relsem(cible,naviguer,navigateur).
relsem(agent,sportif,gagner).
relsem(cible,défendre,basketteur).
relsem(agent,marathonien,courir).
relsem(agent,sportif,jouer).
relsem(agent,sportif,battre).
relsem(agent,sportif,rencontrer).
relsem(agent,concurrent,vaincre).
relsem(agent,sportif,vaincre).
relsem(agent,nageur,plonger).
relsem(cible,nager,sabre).
relsem(agent,sportif,doper).
relsem(cible,naviguer,kayac).
relsem(agent,ballon,naviguer).
relsem(cible,skier,skieur).
relsem(agent,sportif,disputer).
relsem(cible,marquer,footballer).
relsem(agent,skieur,skier).
relsem(cible,jouer,batteur).
relsem(cible,marquer,basketteur).
relsem(agent,concurrent,disputer).
relsem(agent,basketteur,courir).
relsem(agent,sportif,pratiquer).
relsem(agent,concurrent,doper).
relsem(cible,naviguer,reprise).
relsem(cible,pratiquer,sportif).
relsem(agent,sabre,nager).
relsem(cible,nager,maître-nageur).
relsem(agent,maître-nageur,nager).
relsem(cible,tirer,basketteur).
relsem(agent,footballer,marquer).
relsem(agent,footballeur,marquer).
relsem(agent,footballeur,courir).
relsem(agent,batteur,jouer).
relsem(agent,basketteur,marquer).
relsem(agent,footballeuse,marquer).
relsem(agent,footballeuse,tirer).
relsem(agent,footballeuse,jouer).
relsem(agent,sportif,lancer).
relsem(agent,sportif,perdre).
relsem(agent,sportif,nager).
relsem(cible,lancer,sportif).
relsem(cible,sauter,sportif).
relsem(cible,gagner,sportif).
relsem(cible,perdre,sportif).
relsem(cible,courir,sportif).
relsem(agent,maitre-nageur,nager).
relsem(agent,sportif,tricher).
relsem(agent,sportive,tricher).
relsem(agent,footballeur,tricher).
relsem(cible,marquer,footballeur).
relsem(cible,courir,footballeur).
relsem(cible,jouer,sportif).
relsem(cible,lancer,handballeur).
relsem(cible,courir,footballeuse).
relsem(agent,concurrent,tricher).
relsem(agent,reprise,naviguer).
relsem(cible,nager,sportif).
relsem(cible,tricher,footballeur).
relsem(cible,naviguer,ballon).
relsem(agent,concurrent,battre).
relsem(cible,perdre,club de sport).
relsem(agent,club de sport,perdre).
relsem(cible,lancer,nageur).
relsem(cible,tirer,footballeuse).
relsem(cible,jouer,footballeuse).
relsem(cible,nager,maître nageur).
relsem(cible,marquer,footballeuse).
