relsem(cible,nager,voilier).
relsem(cible,toucher,coronaropathies).
relsem(cible,nager,coq).
relsem(agent,coq,nager).
relsem(cible,marcher,patin).
relsem(agent,kayac,naviguer).
relsem(cible,galoper,cheval).
relsem(cible,sauter,cheval).
relsem(agent,coureur,battre).
relsem(cible,naviguer,monotype).
relsem(agent,corsaire,naviguer).
relsem(cible,courir,marathonien).
relsem(agent,veine,battre).
relsem(cible,tirer,arme).
relsem(cible,nager,archer).
relsem(cible,perdre,Poulidor).
relsem(agent,monotype,naviguer).
relsem(cible,jouer,joueur).
relsem(cible,tricher,joueur).
relsem(cible,gagner,joueur).
relsem(cible,perdre,joueur).
relsem(cible,abandonner,joueur).
relsem(cible,attaquer,planeur).
relsem(cible,plonger,planeur).
relsem(agent,cow-boy,tricher).
relsem(agent,cow-boy,galoper).
relsem(cible,tirer,locomotive).
relsem(cible,galoper,cow-boy).
relsem(cible,tricher,cow-boy).
relsem(agent,voiture de course,freiner).
relsem(agent,équipe,vaincre).
relsem(agent,mulet,porter).
relsem(cible,nager,maitre-nageur).
relsem(cible,naviguer,France).
relsem(cible,jouer,parachutiste).
relsem(cible,sauter,pilote).
relsem(agent,pilote,sauter).
relsem(cible,plonger,manchot).
relsem(cible,chuter,avion).
relsem(cible,marcher,guide).
relsem(agent,tricheur,tricher).
relsem(agent,joueur,tricher).
relsem(cible,tricher,concurrent).
relsem(cible,tricher,champion).
relsem(cible,nager,étoile).
relsem(cible,tricher,vainqueur).
relsem(cible,tricher,gagnant).
relsem(cible,tricher,perdant).
relsem(cible,tricher,sportive).
relsem(cible,tricher,athlète).
relsem(cible,tricher,cycliste).
relsem(cible,tricher,coureur cycliste).
relsem(cible,nager,billard).
relsem(agent,coureur,courir).
relsem(agent,animal,courir).
relsem(agent,voiture,glisser).
relsem(agent,animal,marcher).
relsem(agent,jument,galoper).
relsem(agent,cheval,galoper).
relsem(agent,skieur,glisser).
relsem(agent,patineur,glisser).
relsem(agent,marin,naviguer).
relsem(agent,navigateur,naviguer).
relsem(cible,freiner,poids lourd).
relsem(cible,tricher,joueuse).
relsem(agent,avion,chuter).
relsem(cible,marquer,Ribéry).
relsem(cible,courir,joggeuse).
relsem(cible,battre,concurrent).
relsem(agent,sportif,sauter).
relsem(cible,marcher,cheval).
relsem(cible,jouer,étoile).
relsem(cible,marcher,trotteur).
relsem(cible,défendre,essai).
relsem(cible,marcher,cheval).
relsem(cible,tricher,sportif).
relsem(agent,étoile,sauter).
relsem(cible,jouer,titres).
relsem(cible,porter,mulet).
relsem(cible,battre,veine).
relsem(cible,nager,triathlonien).
relsem(cible,courir,triathlonien).
relsem(agent,sportif,abandonner).
relsem(agent,porteur,porter).
relsem(cible,tricher,tricheur).
relsem(agent,luge,glisser).
relsem(cible,vaincre,équipe).
relsem(cible,jouer,cavalier).
relsem(cible,battre,coureur).
relsem(cible,courir,guide).
relsem(agent,leader,mener).
relsem(agent,meneur,mener).
relsem(cible,vaincre,joueur).
relsem(cible,vaincre,gagnant).
relsem(cible,porter,cheval).
relsem(agent,athlète,courir).
relsem(agent,cheval,courir).
relsem(agent,sportif,courir).
relsem(cible,battre,équipe).
relsem(agent,marcheur,marcher).
relsem(cible,battre,champion).
relsem(cible,gagner,compétiteur).
relsem(agent,champion,mener).
relsem(cible,jongler,acrobate).
relsem(agent,route,glisser).
relsem(agent,ski,glisser).
relsem(cible,gagner,champion).
relsem(cible,battre,joueur).
relsem(cible,doper,concurrent).
relsem(agent,titres,jouer).
relsem(cible,disputer,coureur).
relsem(cible,toucher,joie).
relsem(cible,jouer,animal).
relsem(cible,placer,joueur).
relsem(cible,disputer,concurrent).
relsem(cible,disputer,joueur).
relsem(cible,disputer,adversaire).
relsem(cible,courir,basketteur).
relsem(cible,disputer,sportif).
relsem(cible,marcher,appareil).
relsem(cible,attaquer,animal).
relsem(cible,doper,sportif).
relsem(cible,doper,cycliste).
relsem(cible,rencontrer,voiture).
relsem(cible,doper,entraîneur).
relsem(cible,vaincre,concurrent).
relsem(cible,vaincre,sportif).
relsem(cible,attaquer,attaquant).
relsem(cible,plonger,plongeur).
relsem(cible,plonger,nageur).
relsem(cible,rencontrer,équipe).
relsem(cible,rencontrer,sportif).
relsem(cible,freiner,vélo).
relsem(cible,freiner,voiture).
relsem(cible,toucher,doigt).
relsem(cible,toucher,main).
relsem(agent,patin,glisser).
relsem(cible,glisser,surfeur).
relsem(cible,battre,sportif).
relsem(cible,courir,sprinter).
relsem(cible,gagner,gagnant).
relsem(cible,gagner,vainqueur).
relsem(cible,glisser,ski).
relsem(cible,glisser,route).
relsem(cible,courir,cheval).
relsem(cible,courir,athlète).
relsem(cible,marcher,marcheur).
relsem(cible,mener,champion).
relsem(cible,porter,porteur).
relsem(cible,abandonner,sportif).
relsem(cible,glisser,luge).
relsem(cible,mener,meneur).
relsem(cible,mener,leader).
relsem(cible,glisser,voiture).
relsem(cible,galoper,jument).
relsem(cible,glisser,patineur).
relsem(cible,glisser,skieur).
relsem(cible,naviguer,navigateur).
relsem(agent,moule,nager).
relsem(agent,canot,naviguer).
relsem(agent,vainqueur,gagner).
relsem(agent,joueur,gagner).
relsem(agent,gagnant,gagner).
relsem(agent,sportif,gagner).
relsem(cible,défendre,basketteur).
relsem(agent,coureur,gagner).
relsem(agent,marathonien,courir).
relsem(agent,sportif,jouer).
relsem(agent,joueur,jouer).
relsem(cible,nager,truite commune).
relsem(cible,courir,cycliste).
relsem(agent,sprinter,courir).
relsem(agent,surfeur,glisser).
relsem(agent,sportif,battre).
relsem(agent,triathlonien,courir).
relsem(agent,triathlonien,nager).
relsem(agent,main,toucher).
relsem(agent,doigt,toucher).
relsem(agent,sportif,rencontrer).
relsem(agent,équipe,rencontrer).
relsem(agent,vélo,freiner).
relsem(agent,voiture,freiner).
relsem(agent,train,freiner).
relsem(agent,concurrent,vaincre).
relsem(agent,sportif,vaincre).
relsem(agent,attaquant,attaquer).
relsem(cible,nager,Delphinus).
relsem(agent,nageur,plonger).
relsem(agent,plongeur,plonger).
relsem(agent,cow-boy,tirer).
relsem(cible,nager,perche).
relsem(cible,nager,sabre).
relsem(cible,nager,truite).
relsem(cible,nager,lieu).
relsem(cible,nager,merlu).
relsem(cible,nager,capitaine).
relsem(cible,nager,lieu).
relsem(cible,nager,spatule).
relsem(cible,nager,mulet).
relsem(agent,cycliste,doper).
relsem(agent,sportif,doper).
relsem(agent,Mars,naviguer).
relsem(agent,voiture,rencontrer).
relsem(agent,soleil,nager).
relsem(cible,attaquer,jet).
relsem(agent,entraîneur,doper).
relsem(cible,jouer,double).
relsem(cible,naviguer,kayac).
relsem(agent,cardiopathie coronarienne,toucher).
relsem(agent,coronaropathie,toucher).
relsem(agent,insuffisance coronarienne,toucher).
relsem(agent,maladie coronarienne,toucher).
relsem(cible,glisser,patin à glace).
relsem(agent,ballon,naviguer).
relsem(agent,animal,attaquer).
relsem(agent,voilier,nager).
relsem(agent,appareil,marcher).
relsem(cible,nager,merlu commun).
relsem(cible,jouer,ton neutre).
relsem(cible,skier,Kojevnikova).
relsem(agent,jet,attaquer).
relsem(cible,lancer,lanceur).
relsem(cible,skier,skieur).
relsem(cible,supporter,supporteur).
relsem(cible,sauter,sauteur).
relsem(cible,tirer,tireur).
relsem(cible,arrêter,gendarme).
relsem(cible,stopper,stoppeur).
relsem(cible,courir,lièvre).
relsem(agent,truite commune,nager).
relsem(cible,nager,manchot).
relsem(agent,sportif,disputer).
relsem(agent,cycliste,courir).
relsem(cible,marcher,scout).
relsem(agent,sauteur,sauter).
relsem(agent,tireur,tirer).
relsem(agent,lanceur,lancer).
relsem(cible,marquer,footballer).
relsem(cible,sauter,étoile).
relsem(agent,supporteur,supporter).
relsem(agent,Ribéry,marquer).
relsem(agent,stoppeur,stopper).
relsem(agent,skieur,skier).
relsem(cible,jouer,batteur).
relsem(agent,France,naviguer).
relsem(cible,marquer,volleyeur).
relsem(cible,marquer,adversaire).
relsem(cible,marquer,basketteur).
relsem(agent,vache,nager).
relsem(agent,rocher,nager).
relsem(agent,kayak,naviguer).
relsem(agent,gendarme,nager).
relsem(agent,vache,marcher).
relsem(cible,nager,puma).
relsem(agent,manchot,nager).
relsem(agent,tortue,plonger).
relsem(agent,tortue,nager).
relsem(agent,tortue,marcher).
relsem(agent,concurrent,disputer).
relsem(agent,poule,marcher).
relsem(agent,lièvre,courir).
relsem(agent,essai,défendre).
relsem(agent,cavalier,jouer).
relsem(agent,étoile,nager).
relsem(agent,basketteur,courir).
relsem(agent,billard,nager).
relsem(agent,poids lourd,freiner).
relsem(agent,cheval,marcher).
relsem(agent,adversaire,disputer).
relsem(agent,joueur,disputer).
relsem(agent,criquet,sauter).
relsem(agent,voiture,stopper).
relsem(agent,vache,courir).
relsem(agent,double,jouer).
relsem(agent,Kojevnikova,skier).
relsem(agent,planeur,plonger).
relsem(agent,cheval,sauter).
relsem(agent,arme,tirer).
relsem(cible,stopper,voiture).
relsem(agent,voiture>automobile,freiner).
relsem(agent,juge,jouer).
relsem(agent,juge,courir).
relsem(agent,juge,marcher).
relsem(cible,attaquer,F1).
relsem(agent,supporter,supporter).
relsem(agent,animal,galoper).
relsem(agent,joie,toucher).
relsem(agent,coureur,disputer).
relsem(cible,porter,mer).
relsem(agent,mer,porter).
relsem(agent,animal,jouer).
relsem(agent,joueur,placer).
relsem(agent,sportif,pratiquer).
relsem(cible,tirer,gardien de but).
relsem(cible,courir,vache).
relsem(cible,tirer,avion).
relsem(agent,concurrent,doper).
relsem(cible,naviguer,catamaran).
relsem(cible,naviguer,voilier).
relsem(cible,naviguer,canot).
relsem(cible,marcher,poule).
relsem(cible,attaquer,chasse).
relsem(agent,gardien de but,tirer).
relsem(cible,siffler,train).
relsem(cible,freiner,voiture de course).
relsem(agent,joueur,battre).
relsem(agent,coronaropathies,toucher).
relsem(cible,courir,sprinteur).
relsem(cible,doper,entraineur).
relsem(cible,naviguer,reprise).
relsem(agent,acrobate,jongler).
relsem(agent,juvénile,jouer).
relsem(cible,nager,moule).
relsem(agent,champion,gagner).
relsem(agent,puma,nager).
relsem(agent,voilier,naviguer).
relsem(agent,catamaran,naviguer).
relsem(agent,F1,attaquer).
relsem(agent,train,siffler).
relsem(agent,chasse,attaquer).
relsem(cible,pratiquer,sportif).
relsem(cible,stopper,voiture).
relsem(cible,gagner,coureur).
relsem(cible,courir,coureur).
relsem(cible,galoper,coureur).
relsem(cible,perdre,coureur).
relsem(cible,sauter,coureur).
relsem(agent,voiture,stopper).
relsem(agent,mulet,nager).
relsem(cible,nager,pagelle).
relsem(agent,lieu,nager).
relsem(agent,spatule,nager).
relsem(agent,sabre,nager).
relsem(agent,truite,nager).
relsem(agent,merlu,nager).
relsem(agent,lieu,nager).
relsem(agent,capitaine,nager).
relsem(agent,perche,nager).
relsem(cible,nager,maître-nageur).
relsem(agent,archer,tirer).
relsem(cible,courir,sprinter).
relsem(agent,sprinter,courir).
relsem(agent,maître-nageur,nager).
relsem(cible,marcher,pilote).
relsem(cible,perdre,joueuse).
relsem(cible,participer,joueuse).
relsem(cible,mener,leadeur).
relsem(cible,pratiquer,vainqueur).
relsem(cible,sauter,vainqueur).
relsem(cible,jouer,vainqueur).
relsem(cible,vaincre,vainqueur).
relsem(agent,vainqueur,sauter).
relsem(agent,vainqueur,vaincre).
relsem(agent,vainqueur,pratiquer).
relsem(agent,vainqueur,jouer).
relsem(agent,Delphinus,nager).
relsem(cible,tirer,basketteur).
relsem(agent,footballer,marquer).
relsem(cible,marcher,cow-boy).
relsem(cible,tirer,cow-boy).
relsem(agent,OM,perdre).
relsem(agent,OM,gagner).
relsem(agent,cycliste,perdre).
relsem(agent,cycliste,gagner).
relsem(agent,cycliste,chuter).
relsem(agent,albatros,plonger).
relsem(agent,judoka,vaincre).
relsem(agent,judoka,perdre).
relsem(agent,entraineur,doper).
relsem(agent,truite,sauter).
relsem(agent,springbok,courir).
relsem(agent,springbok,sauter).
relsem(agent,avion,plonger).
relsem(agent,avion,attaquer).
relsem(agent,girafe,courir).
relsem(agent,footballeur,marquer).
relsem(agent,footballeur,courir).
relsem(agent,bonification,toucher).
relsem(agent,locomotive,freiner).
relsem(agent,batteur,jouer).
relsem(agent,jument,courir).
relsem(agent,poisson,sauter).
relsem(agent,poisson,nager).
relsem(agent,poisson,attaquer).
relsem(agent,adversaire,marquer).
relsem(agent,volleyeur,marquer).
relsem(agent,basketteur,marquer).
relsem(agent,joueuse,participer).
relsem(agent,joueuse,perdre).
relsem(agent,gendarme,arrêter).
relsem(agent,joggeuse,courir).
relsem(agent,patin,marcher).
relsem(agent,footballeuse,marquer).
relsem(agent,footballeuse,tirer).
relsem(agent,footballeuse,jouer).
relsem(agent,cowboy,tirer).
relsem(agent,patin à glace,glisser).
relsem(agent,joueuse,gagner).
relsem(agent,joueuse,jouer).
relsem(agent,joueuse,vaincre).
relsem(agent,joueur,perdre).
relsem(agent,joueur,abandonner).
relsem(agent,locomotive,tirer).
relsem(agent,Poulidor,perdre).
relsem(agent,guide,marcher).
relsem(agent,sportif,lancer).
relsem(agent,sportif,perdre).
relsem(agent,coureur,galoper).
relsem(agent,coureur,perdre).
relsem(agent,coureur,sauter).
relsem(agent,sportif,nager).
relsem(agent,marin,nager).
relsem(agent,patin,porter).
relsem(cible,tirer,cowboy).
relsem(cible,marquer,marqueur).
relsem(agent,pagelle,nager).
relsem(cible,lancer,sportif).
relsem(cible,sauter,sportif).
relsem(cible,gagner,sportif).
relsem(cible,perdre,sportif).
relsem(cible,courir,sportif).
relsem(cible,nager,vache).
relsem(cible,skier,Kojevnikova).
relsem(agent,marqueur,marquer).
relsem(agent,Kojevnikova,skier).
relsem(agent,équipe,battre).
relsem(agent,champion,battre).
relsem(cible,nager,rocher).
relsem(agent,compétiteur,gagner).
relsem(agent,maitre-nageur,nager).
relsem(cible,nager,gendarme).
relsem(agent,ton neutre,jouer).
relsem(cible,tirer,archer).
relsem(cible,nager,poisson).
relsem(cible,attaquer,poisson).
relsem(cible,sauter,poisson).
relsem(agent,sportif,tricher).
relsem(cible,courir,jument).
relsem(agent,cheval,porter).
relsem(cible,freiner,locomotive).
relsem(agent,gendarme,siffler).
relsem(cible,siffler,gendarme).
relsem(cible,nager,marteau).
relsem(agent,cycliste,tricher).
relsem(agent,athlète,tricher).
relsem(agent,sportive,tricher).
relsem(agent,perdant,tricher).
relsem(cible,attaquer,avion).
relsem(cible,plonger,avion).
relsem(agent,vainqueur,tricher).
relsem(agent,gagnant,tricher).
relsem(agent,footballeur,tricher).
relsem(cible,courir,girafe).
relsem(cible,toucher,bonification).
relsem(cible,marquer,footballeur).
relsem(cible,courir,footballeur).
relsem(cible,jouer,sportif).
relsem(cible,sauter,truite).
relsem(agent,gagnant,vaincre).
relsem(cible,jouer,juvénile).
relsem(cible,sauter,springbok).
relsem(cible,courir,springbok).
relsem(cible,lancer,handballeur).
relsem(cible,courir,footballeuse).
relsem(cible,courir,animal).
relsem(cible,marcher,animal).
relsem(agent,concurrent,tricher).
relsem(agent,champion,tricher).
relsem(agent,reprise,naviguer).
relsem(cible,nager,sportif).
relsem(cible,tricher,footballeur).
relsem(cible,glisser,patin).
relsem(cible,porter,patin).
relsem(cible,courir,poisson).
relsem(cible,marcher,poisson).
relsem(cible,nager,marin).
relsem(cible,naviguer,marin).
relsem(agent,corsaire,attaquer).
relsem(cible,attaquer,corsaire).
relsem(agent,manchot,plonger).
relsem(cible,naviguer,ballon).
relsem(agent,joueur,vaincre).
relsem(cible,vaincre,judoka).
relsem(cible,perdre,judoka).
relsem(cible,marcher,vache).
relsem(cible,chuter,cycliste).
relsem(cible,gagner,cycliste).
relsem(cible,perdre,cycliste).
relsem(agent,marteau,nager).
relsem(agent,concurrent,battre).
relsem(cible,galoper,poisson).
relsem(agent,sprinteur,courir).
relsem(cible,perdre,club de sport).
relsem(agent,club de sport,perdre).
relsem(cible,tricher,cowboy).
relsem(cible,galoper,cowboy).
relsem(agent,avion,tirer).
relsem(cible,lancer,nageur).
relsem(cible,marcher,tortue).
relsem(cible,nager,tortue).
relsem(cible,plonger,tortue).
relsem(cible,plonger,albatros).
relsem(agent,archer,nager).
relsem(cible,chuter,alpiniste).
relsem(agent,scout,marcher).
relsem(agent,alpiniste,chuter).
relsem(cible,tirer,footballeuse).
relsem(cible,nager,barreau).
relsem(cible,nager,médaille).
relsem(cible,jouer,footballeuse).
relsem(cible,nager,maître nageur).
relsem(agent,joueuse,tricher).
relsem(cible,perdre,OM).
relsem(cible,gagner,OM).
relsem(agent,bipède,marcher).
relsem(cible,marcher,bipède).
relsem(cible,naviguer,Mars).
relsem(cible,courir,juge).
relsem(cible,jouer,juge).
relsem(cible,marcher,juge).
relsem(cible,marcher,cowboy).
relsem(cible,freiner,train).
relsem(cible,défendre,essai).
relsem(cible,marquer,footballeuse).
relsem(cible,freiner,voiture).
relsem(agent,barreau,nager).
relsem(agent,médaille,nager).
relsem(cible,nager,soleil).
relsem(agent,judoka,gagner).
relsem(cible,gagner,judoka).
relsem(cible,sauter,criquet).
relsem(cible,naviguer,kayak).
relsem(cible,naviguer,corsaire).
relsem(agent,essai,défendre).
relsem(cible,vaincre,joueuse).
relsem(cible,jouer,joueuse).
relsem(cible,gagner,joueuse).
