relsem(patient,concurrent,battre).
relsem(patient,joueur,stopper).
relsem(patient,adversaire,battre).
relsem(patient,adversaire,attaquer).
relsem(patient,but,marquer).
relsem(patient,point,marquer).
relsem(agent,sportif,abandonner).
relsem(agent,cheval,courir).
relsem(agent,sportif,courir).
relsem(patient,essai,marquer).
relsem(agent,vainqueur,gagner).
relsem(agent,joueur,gagner).
relsem(agent,gagnant,gagner).
relsem(agent,sportif,gagner).
relsem(agent,marathonien,courir).
relsem(agent,sportif,jouer).
relsem(agent,joueur,jouer).
relsem(agent,sprinter,courir).
relsem(agent,sportif,battre).
relsem(agent,sportif,rencontrer).
relsem(patient,course,courir).
relsem(patient,marathon,courir).
relsem(agent,concurrent,vaincre).
relsem(agent,sportif,vaincre).
relsem(agent,attaquant,attaquer).
relsem(patient,juge,toucher).
relsem(patient,adversaire,vaincre).
relsem(patient,tir,contrer).
relsem(agent,basketteur,courir).
relsem(agent,cheval,marcher).
relsem(agent,juge,jouer).
relsem(agent,juge,courir).
relsem(agent,juge,marcher).
relsem(patient,judo,pratiquer).
relsem(patient,natation,pratiquer).
relsem(agent,sportif,pratiquer).
relsem(patient,golf,pratiquer).
relsem(patient,sport,pratiquer).
relsem(patient,tennis,pratiquer).
relsem(patient,joueur,jouer).
relsem(agent,joueur,battre).
relsem(agent,champion,gagner).
relsem(patient,partie,jouer).
relsem(patient,boxeur,vaincre).
relsem(agent,vainqueur,vaincre).
relsem(agent,vainqueur,pratiquer).
relsem(agent,vainqueur,jouer).
relsem(agent,footballer,marquer).
relsem(agent,judoka,vaincre).
relsem(agent,footballeur,marquer).
relsem(agent,footballeur,courir).
relsem(patient,basketteur,marquer).
relsem(patient,adversaire,marquer).
relsem(agent,adversaire,marquer).
relsem(agent,basketteur,marquer).
relsem(agent,footballeuse,marquer).
relsem(agent,footballeuse,tirer).
relsem(agent,footballeuse,jouer).
relsem(agent,joueuse,gagner).
relsem(agent,joueuse,jouer).
relsem(agent,joueuse,vaincre).
relsem(agent,joueur,abandonner).
