vt(abandonne,P,Q,sing,hum,X).
vt(abandonnent,P,Q,plur,hum,X).
vt(accélère,P,Q,sing,hum,X).
vt(accèlerent,P,Q,plur,hum,X).
vt(admire,P,Q,sing,hum,X).
vt(admirent,P,Q,plur,hum,X).
vt(affronte,P,Q,sing,hum,hum).
vt(affrontent,P,Q,plur,hum,hum).
vt(aide,P,Q,sing,hum,hum).
vt(aident,P,Q,plur,hum,hum).
vt(aime,P,Q,sing,hum,nhum).
vt(aiment,P,Q,plur,hum,nhum).
vt(ajoute,P,Q,sing,hum,X).
vt(ajoutent,P,Q,plur,hum,X).
vi(va,P,Q,sing,hum).
vi(vont,P,Q,plur,hum).
vt(améliore,P,Q,sing,hum,nhum).
vt(améliorent,P,Q,plur,hum,nhum).
vt(amortit,P,Q,sing,hum,nhum).
vt(amortissent,P,Q,plur,hum,nhum).
vt(applaudit,P,Q,sing,hum,hum).
vt(applaudissent,P,Q,plur,hum,hum).
vt(arrête,P,Q,sing,hum,X).
vt(arrêtent,P,Q,plur,hum,X).
vi(arrête,P,Q,sing,hum).
vi(arrêtent,P,Q,plur,hum).
vt(arrive,P,Q,sing,hum,nhum).
vt(arrivent,P,Q,plur,hum,nhum).
vt(attaque,P,Q,sing,hum,X).
vt(attaquent,P,Q,plur,hum,X).
vt(attrape,P,Q,sing,hum,X).
vt(attrapent,P,Q,plur,hum,X).
vt(avance,P,Q,sing,hum,nhum).
vt(avancent,P,Q,plur,hum,nhum).
vi(avance,P,Q,sing,hum).
vi(avancent,P,Q,plur,hum).
vt(a,P,Q,sing,hum,nhum).
vt(ont,P,Q,plur,hum,nhum).
vi(appartient,P,Q,sing,hum).
vi(appartiennent,P,Q,plur,hum).
vt(danse,P,Q,sing,hum,nhum).
vt(dansent,P,Q,plur,hum,nhum).
vi(danse,P,Q,sing,hum).
vi(dansent,P,Q,plur,hum).
vt(défend,P,Q,sing,hum,X).
vt(défendent,P,Q,plur,hum,X).
vt(défie,P,Q,sing,hum,hum).
vt(défient,P,Q,plur,hum,hum).
vt(dégage,P,Q,sing,hum,X).
vt(dégagent,P,Q,plur,hum,X).
vi(dégage,P,Q,sing,hum).
vi(dégagent,P,Q,plur,hum).
vt(démarre,P,Q,sing,hum,nhum).
vt(démarrent,P,Q,plur,hum,nhum).
vi(démarre,P,Q,sing,hum).
vi(démarrent,P,Q,plur,hum).
vt(dévie,P,Q,sing,hum,X).
vt(dévient,P,Q,plur,hum,X).
vi(dévie,P,Q,sing,hum).
vi(dévient,P,Q,plur,hum).
vt(dope,P,Q,sing,hum,hum).
vt(dopent,P,Q,plur,hum,hum).
vi(dort,P,Q,sing,hum).
vi(dorment,P,Q,plur,hum).
vt(doit,P,Q,sing,hum,X).
vt(doivent,P,Q,plur,hum,X).
vt(dit,P,Q,sing,hum,nhum).
vt(disent,P,Q,plur,hum,nhum).
vt(dispute,P,Q,sing,hum,hum).
vt(disputent,P,Q,plur,hum,hum).
vt(domine,P,Q,sing,hum,X).
vt(dominent,P,Q,plur,hum,X).
vt(donne,P,Q,sing,hum,nhum).
vt(donnent,P,Q,plur,hum,nhum).
vi(donne,P,Q,sing,hum).
vi(donnent,P,Q,plur,hum).
vi(hésite,P,Q,sing,hum).
vi(hésitent,P,Q,plur,hum).
vt(humilie,P,Q,sing,hum,nhum).
vt(humilient,P,Q,plur,hum,nhum).
vt(jette,P,Q,sing,hum,nhum).
vt(jettent,P,Q,plur,hum,nhum).
vt(jongle,P,Q,sing,hum,nhum).
vt(jonglent,P,Q,plur,hum,nhum).
vt(joue,P,Q,sing,hum,nhum).
vt(jouent,P,Q,plur,hum,nhum).
vi(joue,P,Q,sing,hum).
vi(jouent,P,Q,plur,hum).
vt(lâche,P,Q,sing,hum,nhum).
vt(lâchent,P,Q,plur,hum,nhum).
vi(lâche,P,Q,sing,hum).
vi(lâchent,P,Q,plur,hum).
vt(lance,P,Q,sing,hum,nhum).
vt(lancent,P,Q,plur,hum,nhum).
vt(loupe,P,Q,sing,hum,nhum).
vt(loupent,P,Q,plur,hum,nhum).
vi(loupe,P,Q,sing,hum).
vi(loupent,P,Q,plur,hum).
vi(nage,P,Q,sing,hum).
vi(nagent,P,Q,plur,hum).
vi(navigue,P,Q,sing,hum).
vi(naviguent,P,Q,plur,hum).
vi(provient,P,Q,sing,hum).
vi(proviennent,P,Q,plur,hum).
vt(protège,P,Q,sing,hum,nhum).
vt(protègent,P,Q,plur,hum,nhum).
vi(progresse,P,Q,sing,hum).
vi(progressent,P,Q,plur,hum).
vt(prend,P,Q,sing,hum,X).
vt(prennent,P,Q,plur,hum,X).
vi(prend,P,Q,sing,hum).
vi(prennent,P,Q,plur,hum).
vt(pratique,P,Q,sing,hum,nhum).
vt(pratiquent,P,Q,plur,hum,nhum).
vt(plonge,P,Q,sing,hum,hum).
vt(plongent,P,Q,plur,hum,hum).
vi(plonge,P,Q,sing,hum).
vi(plongent,P,Q,plur,hum).
vt(perd,P,Q,sing,hum,X).
vt(perdent,P,Q,plur,hum,X).
vi(perd,P,Q,sing,hum).
vi(perdent,P,Q,plur,hum).
vi(part,P,Q,sing,hum).
vi(partent,P,Q,plur,hum).
vi(participe,P,Q,sing,hum).
vi(participent,P,Q,plur,hum).
vi(parle,P,Q,sing,hum).
vi(parlent,P,Q,plur,hum).
vt(recrute,P,Q,sing,hum,hum).
vt(recrutent,P,Q,plur,hum,hum).
vt(rejoint,P,Q,sing,hum,X).
vt(rejoignent,P,Q,plur,hum,X).
vt(remplace,P,Q,sing,hum,hum).
vt(remplacent,P,Q,plur,hum,hum).
vt(remporte,P,Q,sing,hum,nhum).
vt(remportent,P,Q,plur,hum,nhum).
vt(rencontre,P,Q,sing,hum,hum).
vt(rencontrent,P,Q,plur,hum,hum).
vt(respecte,P,Q,sing,hum,hum).
vt(respectent,P,Q,plur,hum,hum).
vt(utilise,P,Q,sing,hum,nhum).
vt(utilisent,P,Q,plur,hum,nhum).
vt(saisit,P,Q,sing,hum,nhum).
vt(saisissent,P,Q,plur,hum,nhum).
vt(salue,P,Q,sing,hum,hum).
vt(saluent,P,Q,plur,hum,hum).
vi(saute,P,Q,sing,hum).
vi(sautent,P,Q,plur,hum).
vt(sélectionne,P,Q,sing,hum,X).
vt(sélectionnent,P,Q,plur,hum,X).
vt(siffle,P,Q,sing,hum,hum).
vt(sifflent,P,Q,plur,hum,hum).
vi(siffle,P,Q,sing,hum).
vi(sifflent,P,Q,plur,hum).
vi(skie,P,Q,sing,hum).
vi(skient,P,Q,plur,hum).
vt(soigne,P,Q,sing,hum,hum).
vt(soignent,P,Q,plur,hum,hum).
vt(sort,P,Q,sing,hum,nhum).
vt(sortent,P,Q,plur,hum,nhum).
vi(sort,P,Q,sing,hum).
vi(sortent,P,Q,plur,hum).
vt(stoppe,P,Q,sing,hum,X).
vt(stoppent,P,Q,plur,hum,X).
vi(stoppe,P,Q,sing,hum).
vi(stoppent,P,Q,plur,hum).
vi(sue,P,Q,sing,hum).
vi(suent,P,Q,plur,hum).
vt(suit,P,Q,sing,hum,hum).
vt(suivent,P,Q,plur,hum,hum).
vi(suit,P,Q,sing,hum).
vi(suivent,P,Q,plur,hum).
vt(bat,P,Q,sing,hum,hum).
vt(battent,P,Q,plur,hum,hum).
vi(bat,P,Q,sing,hum).
vi(battent,P,Q,plur,hum).
vt(blesse,P,Q,sing,hum,hum).
vt(blessent,P,Q,plur,hum,hum).
vt(bloque,P,Q,sing,hum,Y).
vt(bloquent,P,Q,plur,hum,Y).
vt(boit,P,Q,sing,hum,nhum).
vt(boivent,P,Q,plur,hum,nhum).
vt(bouscule,P,Q,sing,hum,hum).
vt(bousculent,P,Q,plur,hum,hum).
vt(calme,P,Q,sing,hum,hum).
vt(calment,P,Q,plur,hum,hum).
vt(célèbre,P,Q,sing,hum,nhum).
vt(célèbrent,P,Q,plur,hum,nhum).
vt(change,P,Q,sing,hum,Y).
vt(changent,P,Q,plur,hum,Y).
vi(change,P,Q,sing,hum).
vi(changent,P,Q,plur,hum).
vt(choisit,P,Q,sing,hum,X).
vt(choisissent,P,Q,plur,hum,X).
vi(chute,P,Q,sing,hum).
vi(chutent,P,Q,plur,hum).
vt(concède,P,Q,sing,hum,X).
vt(concèdent,P,Q,plur,hum,X).
vt(connaît,P,Q,sing,hum,X).
vt(connaîssent,P,Q,plur,hum,X).
vt(continue,P,Q,sing,hum,nhum).
vt(continuent,P,Q,plur,hum,nhum).
vi(continue,P,Q,sing,hum).
vi(continuent,P,Q,plur,hum).
vt(contre,P,Q,sing,hum,X).
vt(contrent,P,Q,plur,hum,X).
vi(court,P,Q,sing,hum).
vi(courent,P,Q,plur,hum).
vt(fait,P,Q,sing,hum,nhum).
vt(font,P,Q,plur,hum,nhum).
vt(fatigue,P,Q,sing,hum,hum).
vt(fatiguent,P,Q,plur,hum,hum).
vi(fatigue,P,Q,sing,hum).
vi(fatiguent,P,Q,plur,hum).
vt(félicite,P,Q,sing,hum,hum).
vt(félicitent,P,Q,plur,hum,hum).
vt(fête,P,Q,sing,hum,nhum).
vt(fêtent,P,Q,plur,hum,nhum).
vt(frappe,P,Q,sing,hum,X).
vt(frappent,P,Q,plur,hum,X).
vi(freine,P,Q,sing,hum).
vi(freinent,P,Q,plur,hum).
vt(gagne,P,Q,sing,hum,nhum).
vt(gagnent,P,Q,plur,hum,nhum).
vi(galope,P,Q,sing,hum).
vi(galopent,P,Q,plur,hum).
vt(garde,P,Q,sing,hum,nhum).
vt(gardent,P,Q,plur,hum,nhum).
vi(glisse,P,Q,sing,hum).
vi(glissent,P,Q,plur,hum).
vt(maîtrise,P,Q,sing,hum,nhum).
vt(maîtrisent,P,Q,plur,hum,nhum).
vi(marche,P,Q,sing,hum).
vi(marchent,P,Q,plur,hum).
vt(marque,P,Q,sing,hum,hum).
vt(marquent,P,Q,plur,hum,hum).
vi(marque,P,Q,sing,hum).
vi(marquent,P,Q,plur,hum).
vt(mène,P,Q,sing,hum,nhum).
vt(mènent,P,Q,plur,hum,nhum).
vi(mène,P,Q,sing,hum).
vi(mènent,P,Q,plur,hum).
vt(met,P,Q,sing,hum,nhum).
vt(mettent,P,Q,plur,hum,nhum).
vt(observe,P,Q,sing,hum,X).
vt(observent,P,Q,plur,hum,X).
vt(oppose,P,Q,sing,hum,hum).
vt(opposent,P,Q,plur,hum,hum).
vt(qualifie,P,Q,sing,hum,nhum).
vt(qualifient,P,Q,plur,hum,nhum).
vi(qualifie,P,Q,sing,hum).
vi(qualifient,P,Q,plur,hum).
vt(quitte,P,Q,sing,hum,nhum).
vt(quittent,P,Q,plur,hum,nhum).
vt(ralentit,P,Q,sing,hum,Z).
vt(ralentissent,P,Q,plur,hum,Z).
vi(ralentit,P,Q,sing,hum).
vi(ralentissent,P,Q,plur,hum).
vt(ramasse,P,Q,sing,hum,nhum).
vt(ramassent,P,Q,plur,hum,nhum).
vt(réceptionne,P,Q,sing,hum,nhum).
vt(réceptionnent,P,Q,plur,hum,nhum).
vt(recommence,P,Q,sing,hum,Z).
vt(recommencent,P,Q,plur,hum,Z).
vi(recommence,P,Q,sing,hum).
vi(recommencent,P,Q,plur,hum).
vt(récompense,P,Q,sing,hum,hum).
vt(récompensent,P,Q,plur,hum,hum).
vt(vainc,P,Q,sing,hum,hum).
vt(vainquent,P,Q,plur,hum,hum).
vi(vient,P,Q,sing,hum).
vi(viennent,P,Q,plur,hum).
vt(vise,P,Q,sing,hum,nhum).
vt(visent,P,Q,plur,hum,nhum).
vt(voit,P,Q,sing,hum,X).
vt(voient,P,Q,plur,hum,X).
vt(veut,P,Q,sing,hum,nhum).
vt(veulent,P,Q,plur,hum,nhum).
vt(tire,P,Q,sing,hum,nhum).
vt(tirent,P,Q,plur,hum,nhum).
vt(touche,P,Q,sing,hum,Y).
vt(touchent,P,Q,plur,hum,Y).
vi(triche,P,Q,sing,hum).
vi(trichent,P,Q,plur,hum).
vt(trouve,P,Q,sing,hum,X).
vt(trouvent,P,Q,plur,hum,X).
vt(supporte,P,Q,sing,hum,Y).
vt(supportent,P,Q,plur,hum,Y).
vt(suspend,P,Q,sing,hum,X).
vt(suspendent,P,Q,plur,hum,X).
