np(Porsche,P,Q,sing,fem,nhum).
np(Contre,P,Q,sing,masc,nhum).
np(Pato,P,Q,sing,masc,nhum).
np(Ferrero,P,Q,sing,masc,hum).
np(NFL,P,Q,sing,masc,nhum).
np(TREC,P,Q,sing,fem,nhum).
np(Bercy,P,Q,sing,masc,nhum).
np(Puma,P,Q,sing,masc,nhum).
np(Belgique,P,Q,sing,fem,nhum).
np(Genesis,P,Q,sing,fem,nhum).
np(Grèce,P,Q,sing,fem,nhum).
np(Golf,P,Q,sing,fem,nhum).
np(BCT,P,Q,sing,fem,nhum).
np(Ferrari,P,Q,sing,fem,nhum).
np(Taxi,P,Q,sing,masc,nhum).
np(JO,P,Q,sing,masc,nhum).
np(Olympie,P,Q,sing,fem,hum).
np(Dioclès,P,Q,plur,masc,hum).
np(Saint-Maurice,P,Q,sing,masc,nhum).
np(Montblanais,P,Q,sing,masc,hum).
np(Ballesteros,P,Q,sing,fem,nhum).
np(X-board,P,Q,sing,masc,nhum).
np(Loulou,P,Q,sing,fem,hum).
np(Tunisie,P,Q,sing,fem,nhum).
np(Groland,P,Q,sing,masc,nhum).
np(T-shirt,P,Q,sing,masc,nhum).
np(KO,P,Q,sing,masc,nhum).
np(Wii,P,Q,sing,fem,nhum).
np(Sol,P,Q,sing,masc,hum).
np(Australie,P,Q,sing,fem,nhum).
np(Barbidur,P,Q,sing,fem,nhum).
np(Barbidou,P,Q,sing,masc,nhum).
np(Galatasaray,P,Q,sing,masc,nhum).
np(Grande-Bretagne,P,Q,sing,fem,hum).
np(Espagne,P,Q,sing,fem,hum).
np(Noblesse,P,Q,sing,fem,nhum).
np(Nike,P,Q,sing,fem,nhum).
np(Royaume-Uni,P,Q,sing,masc,hum).
np(Brooks,P,Q,sing,masc,nhum).
np(France,P,Q,sing,masc,hum).
np(BMX,P,Q,sing,masc,nhum).
np(Mai,P,Q,sing,fem,hum).
np(Canal+,P,Q,sing,masc,nhum).
np(Bastia,P,Q,sing,masc,nhum).
np(Angleterre,P,Q,sing,fem,hum).
np(Jorkyball,P,Q,sing,masc,nhum).
np(ULM,P,Q,sing,masc,nhum).
np(Tinker,P,Q,sing,masc,hum).
np(Ballon,P,Q,sing,masc,nhum).
np(Allemagne,P,Q,sing,fem,nhum).
np(Monnaie,P,Q,sing,masc,nhum).
np(Jazz,P,Q,sing,masc,hum).
np(Manche,P,Q,sing,fem,nhum).
np(Inde,P,Q,sing,fem,nhum).
np(Chasse,P,Q,sing,masc,nhum).
np(Sicile,P,Q,sing,fem,nhum).
np(Florence,P,Q,sing,fem,hum).
np(Brive-la-Gaillarde,P,Q,sing,masc,nhum).
np(CSO,P,Q,sing,masc,nhum).
np(Asie,P,Q,sing,fem,nhum).
np(Nouvelle-Angleterre,P,Q,sing,fem,nhum).
np(Canada,P,Q,sing,masc,nhum).
np(Discobole,P,Q,plur,masc,nhum).
np(Mars,P,Q,sing,fem,hum).
np(Hewitt,P,Q,sing,masc,nhum).
np(Toronto,P,Q,sing,masc,nhum).
np(Roland-Garros,P,Q,sing,masc,nhum).
np(Péloponnèse,P,Q,sing,masc,nhum).
np(Surf,P,Q,sing,masc,nhum).
np(Brennus,P,Q,sing,masc,nhum).
np(Monopoly,P,Q,sing,masc,nhum).
np(Transition,P,Q,sing,masc,nhum).
np(Panthéon,P,Q,sing,masc,nhum).
np(Rome,P,Q,sing,masc,nhum).
np(Europe,P,Q,sing,fem,hum).
np(Renaissance,P,Q,sing,fem,nhum).
np(Suisse,P,Q,sing,fem,hum).
np(Wimbledon,P,Q,sing,masc,nhum).
np(Italie,P,Q,sing,masc,nhum).
np(Powerball,P,Q,sing,masc,nhum).
np(Euro,P,Q,sing,masc,nhum).
np(Spyder,P,Q,sing,masc,nhum).
np(Calmann-Lévy,P,Q,sing,fem,hum).
np(Centre,P,Q,sing,masc,nhum).
np(Rouge,P,Q,sing,masc,nhum).
np(Flore,P,Q,sing,fem,hum).
np(Occident,P,Q,sing,masc,nhum).
np(Chadwick,P,Q,sing,masc,nhum).
np(Touch,P,Q,sing,masc,nhum).
np(IDM,P,Q,sing,masc,nhum).
np(Noble,P,Q,sing,masc,nhum).
np(Solon,P,Q,sing,masc,hum).
np(F1,P,Q,sing,fem,nhum).
np(Paris,P,Q,sing,masc,hum).
np(Fosbury-flop,P,Q,sing,masc,nhum).
np(Pakistan,P,Q,sing,masc,nhum).
np(Cabinda,P,Q,sing,masc,nhum).
np(Poulidor,P,Q,sing,masc,hum).
np(Monaco,P,Q,sing,masc,nhum).
np(Marche,P,Q,sing,fem,nhum).
np(Londres,P,Q,sing,masc,nhum).
np(Sokol,P,Q,sing,masc,nhum).
np(Amos,P,Q,sing,masc,hum).
np(Junior,P,Q,sing,masc,hum).
np(JO,P,Q,plur,fem,nhum).
